### ISSUE TITLE
VisualEditor gives an unknown error when saving edits, but edit saves successfully

### ISSUE THREAD

**Issue by conneath** [jayktaylor/mw-discord#17]
removing the discord extension seems to fix the issue, can get annoying because it does not redirect you to the article page

**Comment by jayktaylor** [comment]
This doesn't appear to be an issue, at least not anymore. We're running VisualEditor alongside this extension on https://runescape.wiki and edits save fine. If you are still experiencing this issue (I know it has been open for quite a long while), please make a new issue with repro steps and logs and I'll be happy to look into this.
