### ISSUE TITLE
Feature Request: Disable Sandbox Notifications

### ISSUE THREAD

**Issue by d-bergman** [jayktaylor/mw-discord#22]
As title says, It would be great to have a feature where one can disable notification edits for the namespace: User:Name/Sandbox , User:Name/sandbox.

**Comment by jaydenkieran** [comment]
Would it be better to have the option to disable notifications for a pre-defined list of pages? Or maybe matching regex? It would likely have a (minor) performance impact though if the list was big, I'd imagine.

**Comment by jayktaylor** [comment]
Currently, there are no plans to add a feature to exclude specific pages. However, specific namespaces can be excluded using the `$wgDiscordDisabledNS` option.
