### ISSUE TITLE
Unblocks don't include the unblock reason

### ISSUE THREAD

**Issue by Dinoguy1000** [jayktaylor/mw-discord#23]
For example, [the unblock here](https://yugipedia.com/index.php?title=Special:Log/block&page=User%3A142.93.64.0%2F20), which produced this message: 
![image](https://user-images.githubusercontent.com/818183/80332847-ac043580-8811-11ea-8632-336d2a1b04c4.png)

**Comment by jaydenkieran** [comment]
This looks fine when testing locally. Are you sure that MediaWiki:Discord-unblockusercomplete on your wiki is correct? The default i18n file for English has this string down as `$1 unblocked $2`

**Comment by Dinoguy1000** [comment]
That message on our wiki is [identical](https://yugipedia.com/wiki/MediaWiki:Discord-unblockusercomplete) to what you've listed here, yes.

**Comment by jayktaylor** [comment]
Hey! Coming back to this after a little while now that I have lots of time for MW work. It doesn't look like there's an appropriate hook that will provide the unblock reason (weirdly). The reason is only outputted to RC feeds, but this extension intercepts hooks rather than acts as an RC feed.
