### ISSUE TITLE
Rationales/summaries for revision visibility changes aren't shown

### ISSUE THREAD

**Issue by Dinoguy1000** [jayktaylor/mw-discord#30]
![image](https://user-images.githubusercontent.com/818183/103855468-5ce8f280-5078-11eb-9273-3d7ede3f6ab3.png)
![image](https://user-images.githubusercontent.com/818183/103855506-6ffbc280-5078-11eb-9297-5fe6466aab62.png)
(https://yugipedia.com/index.php?title=Special:Log&page=Contact+Fusion)

**Comment by jayktaylor** [comment]
There is currently no hook that provides this functionality in MediaWiki.
