### ISSUE TITLE
edits don't ping on mediawiki 1.37 

### ISSUE THREAD

**Issue by orchardstreet** [jayktaylor/mw-discord#34]
unfortunately

**Comment by orchardstreet** [comment]
This diff I made seems to solve most issues, https://github.com/orchardstreet/mw-discord/commit/dd5fccd7242178e7725ef3f42478de5fd999a952

with Mediawiki 1.37

Except it doesn't output byte diff (just total bytes), and it just says it's editing a page when creating a new page.  Couldn't really figure out how to do byte diff and new page notice with the new function.

**Comment by jaydenkieran** [comment]
Thanks for the heads up. I'll get this sorted soon.

**Comment by jayktaylor** [comment]
Apologies for the delay getting back to this. Can you see whether the [`REL1_36`](https://github.com/jayktaylor/mw-discord/tree/REL1_36) branch fixes your issues? It should have compatibility with 1.37 unless something has changed dramatically since 1.36 that I haven't quite spotted.

**Comment by ThomasJRyan** [comment]
I was having the same issue. It looks like REL1_36 fixes it. Thank you @jayktaylor !
