### ISSUE TITLE
Page names can be used to ping users (including @here and @everyone)

### ISSUE THREAD

**Issue by Dinoguy1000** [jayktaylor/mw-discord#42]
![image](https://user-images.githubusercontent.com/818183/163854255-30988738-74ab-4bef-91e6-4a9651825530.png)

**Comment by Dinoguy1000** [comment]
Probably the same fix as #10 but considering the potential for notification spam, this is higher priority.

**Comment by jayktaylor** [comment]
Thanks. This is being resolved as a high priority.
