### ISSUE TITLE
File::getUser is deprecated since 1.37 and removed in 1.38, breaking uploads

### ISSUE THREAD

**Issue by ihaveamac** [jayktaylor/mw-discord#43]
Because of this removal, uploading files results in this error:
`/wiki/Special:Upload Error: Call to undefined method LocalFile::getUser()`

This is the line:
https://github.com/jayktaylor/mw-discord/blob/80f28e59205948160580fa77e0ac3d94229ee56e/src/DiscordHooks.php#L284

**Comment by ihaveamac** [comment]
Replacing the line with this worked for me but I don't know if it's the right way to go at this since my experience with MW development is limited.

```php
$user = MediaWikiServices::getInstance()->getUserFactory()->newFromUserIdentity( $lf->getUploader() );
```

**Comment by jayktaylor** [comment]
Thanks. I'll look at this today, but your code change seems more or less correct 👍

**Comment by jayktaylor** [comment]
This should be resolved by https://github.com/jayktaylor/mw-discord/commit/96070a653879c63ead3d69e8ce7847d630a422b8.
