### ISSUE TITLE
No messages are sent on Mediawiki 1.39

### ISSUE THREAD

**Issue by alhockly** [jayktaylor/mw-discord#44]
I haven't tested all the hooks but I no longer receive messages from the bot for page edits or uploads after upgrading to 1.39.  I have also tried reinstalling the extension.

**Comment by jayktaylor** [comment]
Hello, I've tried running the extension on a fresh MediaWiki 1.39.1 installation. Editing a page and uploading a new file seems to work fine and triggers the webhook in Discord. Could you check your server's error logs for anything related to the extension?

**Comment by alhockly** [comment]
Hi @jayktaylor, I've enabled errors on the webpage by adding `error_reporting( -1 ); ini_set( 'display_errors', 1 );` to the top of LocalSettings.php but I don't see any errors related to the discord extension. Is there another place to look for errors?

Thanks

**Comment by jayktaylor** [comment]
PHP related errors from the extension may be seen inside your PHP/web server logs.

You could also look at your [debug log](https://www.mediawiki.org/wiki/Manual:$wgDebugLogFile) which may contain debug messages coming from the `discord` logging channel. The extension should log problems that it encounters that aren't necessarily fatal issues in that log.

You can [selectively log](https://www.mediawiki.org/wiki/Manual:$wgDebugLogGroups) this using something like:

```php
$wgDebugLogGroups['discord'] = '/var/log/mediawiki/redis.log';
```
