### ISSUE TITLE
$wgDiscordDisabledNS works?

### ISSUE THREAD

**Issue by burner1024** [jayktaylor/mw-discord#53]
So I have `$wgDiscordDisabledNS = ["MediaWiki"];` set, and still get notifications for `MediaWiki:Common.css`.
Am I doing something wrong?
This is on 1.39.

**Comment by jayktaylor** [comment]
Hey, sorry - this could be documented better. The extension expects an array of ints. The ints for the default namespaces are [listed here](https://www.mediawiki.org/wiki/Manual:Namespace#Built-in_namespaces).

To block the MediaWiki namespace, you would set `$wgDiscordDisabledNS = [ 8 ];`. Theoretically, you should also be able to write `$wgDiscordDisabledNS = [ NS_MEDIAWIKI ];` too.

**Comment by burner1024** [comment]
Cool, thanks!
