### ISSUE TITLE
Special:Upload Error: Call to undefined method LocalFile::getUser()

### ISSUE THREAD

**Issue by TarkusLee** [jayktaylor/mw-discord#65]
stack trace provided by user in the attached image

![image](https://github.com/user-attachments/assets/5958420b-5f0c-4a1c-a861-2d53bdc80eea)

**Comment by jayktaylor** [comment]
Hey, can you share what version of MediaWiki you are using and the version of the extension (from Special:Version on your wiki)? Thanks!

**Comment by TarkusLee** [comment]
closing ticket because it turns out it was a version mis-match. Sorry for the trouble.
